-- Chạy với quyền SYSTEM
CREATE USER C##LAB1 IDENTIFIED BY 123;
GRANT ALL PRIVILEGES TO C##LAB1;
ALTER USER C##LAB1 QUOTA UNLIMITED ON USERS;

-- Tạo bảng HANGHANGKHONG
CREATE TABLE HANGHANGKHONG (
    MAHANG VARCHAR2(10) PRIMARY KEY,
    TENHANG VARCHAR2(100),
    NGTL DATE,
    DUONGBAY NUMBER
);

-- Tạo bảng CHUYENBAY
CREATE TABLE CHUYENBAY (
    MACB VARCHAR2(10) PRIMARY KEY,
    MAHANG VARCHAR2(10),
    XUATPHAT VARCHAR2(50),
    DIEMDEN VARCHAR2(50),
    BATDAU DATE,
    TGBAY NUMBER,
    CONSTRAINT FK_CB_HANG FOREIGN KEY (MAHANG) REFERENCES HANGHANGKHONG(MAHANG)
);

-- Tạo bảng NHANVIEN
CREATE TABLE NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100),
    GIOITINH VARCHAR2(5),
    NGSINH DATE,
    NGVL DATE,
    CHUYENMON VARCHAR2(50)
);

-- Tạo bảng PHANCONG
CREATE TABLE PHANCONG (
    MACB VARCHAR2(10),
    MANV VARCHAR2(10),
    NHIEMVU VARCHAR2(50),
    CONSTRAINT PK_PHANCONG PRIMARY KEY (MACB, MANV),
    CONSTRAINT FK_PC_CB FOREIGN KEY (MACB) REFERENCES CHUYENBAY(MACB),
    CONSTRAINT FK_PC_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

-- Nhập HANGHANGKHONG
INSERT INTO HANGHANGKHONG VALUES ('VN', 'Vietnam Airlines', TO_DATE('15/01/1956', 'DD/MM/YYYY'), 52);
INSERT INTO HANGHANGKHONG VALUES ('VJ', 'Vietjet Air', TO_DATE('25/12/2011', 'DD/MM/YYYY'), 33);
INSERT INTO HANGHANGKHONG VALUES ('BL', 'Jetstar Pacific Airlines', TO_DATE('01/12/1990', 'DD/MM/YYYY'), 13);

-- Nhập CHUYENBAY (Lưu ý định dạng ngày giờ)
INSERT INTO CHUYENBAY VALUES ('VN550', 'VN', 'TP.HCM', 'Singapore', TO_DATE('20/12/2025 13:15', 'DD/MM/YYYY HH24:MI'), 2);
INSERT INTO CHUYENBAY VALUES ('VJ331', 'VJ', 'Đà Nẵng', 'Vinh', TO_DATE('28/12/2025 22:30', 'DD/MM/YYYY HH24:MI'), 1);
INSERT INTO CHUYENBAY VALUES ('BL696', 'BL', 'TP.HCM', 'Đà Lạt', TO_DATE('24/12/2025 06:00', 'DD/MM/YYYY HH24:MI'), 0.5);

-- Nhập NHANVIEN
INSERT INTO NHANVIEN VALUES ('NV01', 'Lâm Văn Bền', 'Nam', TO_DATE('10/09/1991', 'DD/MM/YYYY'), TO_DATE('05/06/2021', 'DD/MM/YYYY'), 'Phi công');
INSERT INTO NHANVIEN VALUES ('NV02', 'Dương Thị Lục', 'Nữ', TO_DATE('22/03/1989', 'DD/MM/YYYY'), TO_DATE('12/11/2020', 'DD/MM/YYYY'), ' Tiếp viên');
INSERT INTO NHANVIEN VALUES ('NV03', 'Hoàng Thanh Tùng', 'Nam', TO_DATE('29/07/1995', 'DD/MM/YYYY'), TO_DATE('11/04/2022', 'DD/MM/YYYY'), ' Tiếp viên');

-- Nhập PHANCONG
INSERT INTO PHANCONG VALUES ('VN550', 'NV01', 'Cơ trưởng');
INSERT INTO PHANCONG VALUES ('VN550', 'NV02', 'Tiếp viên');
INSERT INTO PHANCONG VALUES ('BL696', 'NV03', 'Tiếp viên trưởng');

COMMIT;

ALTER TABLE NHANVIEN 
ADD CONSTRAINT CHK_CHUYENMON 
CHECK (CHUYENMON IN ('Phi công', 'Tiếp viên'));

CREATE OR REPLACE TRIGGER TRG_CHECK_BATDAU
BEFORE INSERT OR UPDATE ON CHUYENBAY
FOR EACH ROW
DECLARE
    v_ngtl DATE;
BEGIN
    SELECT NGTL INTO v_ngtl 
    FROM HANGHANGKHONG 
    WHERE MAHANG = :NEW.MAHANG;
    
    IF (:NEW.BATDAU <= v_ngtl) THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ngay bat dau chuyen bay phai lon hon ngay thanh lap hang!');
    END IF;
END;
/

SELECT * FROM NHANVIEN 
WHERE EXTRACT(MONTH FROM NGSINH) = 7;

SELECT * FROM (
    SELECT MACB, COUNT(MANV) AS SO_NV
    FROM PHANCONG
    GROUP BY MACB
    ORDER BY SO_NV DESC
) WHERE ROWNUM = 1;

SELECT H.TENHANG, COUNT(CB.MACB) AS SO_LUONG_CB
FROM HANGHANGKHONG H
LEFT JOIN CHUYENBAY CB ON H.MAHANG = CB.MAHANG AND CB.XUATPHAT = 'Đà Nẵng'
WHERE CB.MACB IS NULL OR CB.MACB IN (
    SELECT MACB 
    FROM PHANCONG 
    GROUP BY MACB 
    HAVING COUNT(MANV) < 2
)
GROUP BY H.TENHANG;

SELECT * FROM NHANVIEN NV
WHERE NOT EXISTS (
    SELECT MACB FROM CHUYENBAY
    MINUS
    SELECT MACB FROM PHANCONG PC WHERE PC.MANV = NV.MANV
);